### ISSUE TITLE
githubtify

### ISSUE THREAD

**Issue by imaaquibali** [codedamn/projects#105]
I would like to create a project where users can Fork other's Playlist Create Issues on their albums Send PRs for collaboration.

Kindly assign this issue to me and consider it as a contribution for hacktoberfest22.

**Comment by Pranavtechie** [comment]
Hey @imaaquibali, can you describe the project in-detail, below

**Comment by imaaquibali** [comment]
@Pranavtechie I'm closing this issue cause it's but confusing for the folks
