### ISSUE TITLE
e-commerce-site

### ISSUE THREAD

**Issue by imaaquibali** [codedamn/projects#106]
I'd like to create an e-commerce guided project
Kindly assign this issue to me and consider it as a contribution for hacktoberfest22.

**Comment by imaaquibali** [comment]
@Pranavtechie can you  have look on it!

**Comment by Pranavtechie** [comment]
Hey @imaaquibali , you can work on this project as well

**Comment by imaaquibali** [comment]
@Pranavtechie Brother i created an PR for this issue please have a look on it.

PR number #109

**Comment by sumitbaroniya** [comment]
Please assign me this issue.

**Comment by imaaquibali** [comment]
@sumitbaroniya brother I'm already working at this issue!

**Comment by Sonali3110** [comment]
I have already create many of these.I can customize according to your needs.Please assign me this

**Comment by imaaquibali** [comment]
@Pranavtechie Brother, there is no updates on this issue. Is there any problem?
