### ISSUE TITLE
Personal Portfolio Website

### ISSUE THREAD

**Issue by ravi0900** [codedamn/projects#114]
I'd like to create an personal portfolio website guided project
Kindly assign this issue to me and consider it as a contribution for hacktoberfest22.

**Comment by ravi0900** [comment]
#126

**Comment by sumitbaroniya** [comment]
Please assign me this issue

**Comment by Dhanshriborse** [comment]
Please assign this issue to me .

**Comment by ravi0900** [comment]
> Please assign me this issue

Please create a issue to work on, it's me who working on it

**Comment by ravi0900** [comment]
> Please assign this issue to me .

Please create a issue to work on, it's me who working on it
