### ISSUE TITLE
Dice Game Project

### ISSUE THREAD

**Issue by BarmenduC** [codedamn/projects#116]
I would like to add an interactive dice game as a guided project in codedamn-projects for hacktoberfest. It is a simple game which declares the winner on the basis of who(amongst two players) gets the highest number generated from the roll of the dice. It can be easily made with the help of HTML, CSS and a little Javascript.

**Comment by FixxooXD** [comment]
OK am interested in this project , so starting to work on this i will be using HTML, TAILWINDCSS, AND VANILA JS so is  it  ok ?

**Comment by BarmenduC** [comment]
Yes, for this project HTML, CSS(Vanilla or Tailwind depending upon the
comfort of the developer) and Vanilla JS are adequate.

**Comment by yashdkadam** [comment]
I would like to contribute to this issue. Could you please assign me this issue?
