### ISSUE TITLE
A Blog Page

### ISSUE THREAD

**Issue by amanverma2253** [codedamn/projects#117]
I would like to add blog page project. Kindly assign this issue to me and consider it as a contribution for hacktoberfest22.

**Comment by geetika001** [comment]
Hey @Pranavtechie I have added a PR  #145 for this project. Please review and do accept the PR.

**Comment by geetika001** [comment]
Hey @Pranavtechie I have added PR #145 for this Project.Please review and do accept the PR.
Please assign me this task and requesting you to consider for Hacktoberfest.

**Comment by geetika001** [comment]
Few Screenshots to show how it looks

![image](https://user-images.githubusercontent.com/98944568/194937750-9a1e3484-3c31-4b63-9f20-e16c43cbf83c.png)
![image](https://user-images.githubusercontent.com/98944568/194937792-338722cc-b027-4359-bafb-7316483891d5.png)
![image](https://user-images.githubusercontent.com/98944568/194937848-6a2857a6-f5b7-44f3-a0fd-78d59611f230.png)
![image](https://user-images.githubusercontent.com/98944568/194937890-38b2e5f0-b203-47b3-806e-26fba88112af.png)
