### ISSUE TITLE
Adding Netflix Clone Website (FakeFlix)

### ISSUE THREAD

**Issue by ShivamAgarwal-code** [codedamn/projects#127]

**Comment by ShivamAgarwal-code** [comment]
Consider it as a contribution for Hacktoberfest..

**Comment by ShivamAgarwal-code** [comment]
Hello I want to add resume generator website, please assign me this issue asap..

**Comment by ShivamAgarwal-code** [comment]
@mehulmpt sir can u please assign me the issue so that I could work on making pr fast..

**Comment by mehulmpt** [comment]
I'm nto sure if I understand this request?

**Comment by ShivamAgarwal-code** [comment]
Should I tell about the website features?
It's a clone of Netflix, will be using tech stacks like react, firebase, js, some others and also enhancing some other features in the website..
So please consider the request and assign it...

**Comment by mehulmpt** [comment]
Sure, you can work on it. Please send a PR when you're ready
