### ISSUE TITLE
A Guided Project to demonstrate API call with HTML, CSS, JS

### ISSUE THREAD

**Issue by SSHSRN** [codedamn/projects#129]
I would like to add a guided project to make people understand the concept of fetching data from an API. Kindly assign this issue to me and consider it as a contribution for hacktoberfest22.

**Comment by Purvesh77** [comment]
Hey @SSHSRN I have uploaded a code in html which uses API and gives our location in the form of latitude and longitude
Can You merge it ?
Thank You
PR: Create Html With API #131

**Comment by SSHSRN** [comment]
> Hey @SSHSRN I have uploaded a code in html which uses API and gives our location in the form of latitude and longitude Can You merge it ? Thank You PR: Create Html With API #131

Hey @Purvesh77. Thanks for reaching out, but unfortunately, I'm just a fellow contributor like you too and I do not have the access to merge PRs. And I also saw your PR. It's so basic and you have not even added any CSS to it. You have just called the Geolocation API using the navigator object to get the user's latitude and longitude and for someone who does not even know what latitude and longitude is. You can try adding some feature to visualize the latitude and longitude of the user in a map so that it is understandable. 

Actually, I had some more features planned to implement.

**Comment by SSHSRN** [comment]
@Pranavtechie Kindly assign me this issue as I want to make a guided project that helps students know about APIs and consider it as a contribution for **hacktoberfest22**.
