### ISSUE TITLE
Currency Converter 

### ISSUE THREAD

**Issue by Princeton21** [codedamn/projects#139]
I will be working on a currency converter using ReactJS.
Kindly assign me this issue.

This is a contribution for Hacktoberfest 2022

**Comment by Pranavtechie** [comment]
Hey @Princeton21 , you can start working on the guided project

**Comment by Nikhil-2002** [comment]
I will be working on a currency converter using Java
Kindly assign me this issue

**Comment by anshulsoni2010** [comment]
Please assign me , I have just created a currency converter app using HTML, CSS,JavaScript . repo link - https://github.com/anshulsoni2010/Currency-converter-

**Comment by Princeton21** [comment]
@anshulsoni2010  
I am currently working on this.
