### ISSUE TITLE
Case-converter and Real-Time character counter

### ISSUE THREAD

**Issue by FixxooXD** [codedamn/projects#141]
It is a simple project which can count character in real-time and can covert the case of the letters accordingly like (uppercase, lowercase, capitalized case, title case, and also  if possible I would add  "copy-to-clipboard" and "download text" options .
I will be using  HTML, TAILWINDCSS & VANILLA JS .

Is this will be a Valid Project ? @Pranavtechie

**Comment by Pranavtechie** [comment]
Hey @FixxooXD , yes this is a valid  project. You can start working on the guided project version for this
