### ISSUE TITLE
Snapchat ho.epage clone

### ISSUE THREAD

**Issue by RidhamRj** [codedamn/projects#142]
Cloning snapchat homepage
snapchat.com 

Tech stack used-
- [x] reactjs
- [x] css

I am currently working on this project to furnish my coding skills

Would like to contribute to this repo 

Creating this issue to confirm if this kind of project already exists or not

Kindly review the request and assign me asap...

**Comment by RidhamRj** [comment]
@Pranavtechie Kindly assign
The current development goes as follows
Haven't made it responsive yet
Also I am working on making nav waffle work
Will complete sight soon


Kindly review on desktop
https://snapchat-clone-virid.vercel.app/

**Comment by RidhamRj** [comment]
I would like to contribute in so kindly assign this to me

**Comment by Pranavtechie** [comment]
Hey @RidhamRj , you can work on the guided project version of this

**Comment by RidhamRj** [comment]
@Pranavtechie this wasn't completed

**Comment by RidhamRj** [comment]
why closed

**Comment by RidhamRj** [comment]
> Hey @RidhamRj , you can work on the guided project version of this

what does the guided project version means?

**Comment by mehulmpt** [comment]
Please read the guidelines properly: https://github.com/codedamn/projects#readme
