### ISSUE TITLE
NFT Marketplace Guided Project

### ISSUE THREAD

**Issue by navyansh007** [codedamn/projects#144]
Hello, I would like to contribute the NFT Marketplace Guided project, that guides learners in making an NFT Marketplace using React and Solidity. I would like this to be counted as HacktoberFest2022 Contribution. Please assign this issue to me and add hacktoberfest label to it.

**Comment by Pranavtechie** [comment]
Hey @navyansh007. I see that you have already made the Pull Request https://github.com/codedamn/projects/pull/53

We'll review it soon
