### ISSUE TITLE
Math Training Game

### ISSUE THREAD

**Issue by ritwickrajmakhal** [codedamn/projects#146]
I would like to add a **Math Training Game**, in which we can solve some addition, subtraction, division, multiplication question to improve our verbal calculation. @Pranavtechie please assign me this project and count me in Hactoberfest by labeling my project. Thank you.

**Comment by Pranavtechie** [comment]
Hey @ritwickrajmakhal, yes you can work on this as a guided-project

**Comment by AkanshuAich** [comment]
I would like to add a math Training program for several volume and area of certain figures with several required inputs to be available on the fingertips. A single program further can reduce the work load and calculations. @Pranavtechie please assign me this project and count me inhactoberfest by labelling my project. Thank you.

**Comment by mehulmpt** [comment]
You can work on it. Please send a PR when you're ready. Read the guidelines here: https://github.com/codedamn/projects#readme
