### ISSUE TITLE
Pathfinding with Reinforcement Learning

### ISSUE THREAD

**Issue by Elstuhn** [codedamn/projects#147]
I would like to make a guided project for intermediate programmers to teach them how to make a pathfinding program using one of Reinforcement Learning's many methods, Q-Learning. 

I know it's outside of what your guided projects normally contain, containing website related stuff. But I think it'll be cool if this project was added to teach people about a very interesting field, Reinforcement Learning. Moreover, I think it will be popular.

Please allow me to work on this guided project and label this issue with the Hacktoberfest label to count it towards Hacktoberfest2022

**Comment by mehulmpt** [comment]
What technology/programming language would it require?

**Comment by mehulmpt** [comment]
We support Python (https://codedamn.com/playgrounds?template=python). You can work on it. Please send a PR when you're ready. Read the guidelines here: https://github.com/codedamn/projects#readme
