### ISSUE TITLE
Fetching details of a user's IP address (to create awareness)

### ISSUE THREAD

**Issue by SSHSRN** [codedamn/projects#148]
I would like to add a guided project to make people understand the concept of fetching data from an API and demonstrate it with HTML, CSS, JS. 
I also want to demonstrate what are the details that can be obtained from a user's IP address in this project.

Kindly assign this issue to me and consider it as a contribution for **hacktoberfest22**.

**Comment by SSHSRN** [comment]
@Pranavtechie Kindly check!

**Comment by mehulmpt** [comment]
You can work on it. Please send a PR when you're ready. Read the guidelines here: https://github.com/codedamn/projects#readme
