### ISSUE TITLE
A fullstack real-time chat app with auth, More like a telegram clone

### ISSUE THREAD

**Issue by amitanshusahu** [codedamn/projects#149]
## building a  "Real time chat app" with MERN stack
how to approach 
- [ ] user auth system with encrypted password using bcrypt
- [ ] a beautiful ui and ux and fully resposive
- [ ] integrating soket.io to react for making it realtime 
 ### features include
- login , logout , register 
- realtime private chats
- chats saved to databse and users can set time to autoclean chat after a certain time

**Comment by amitanshusahu** [comment]
@Princeton21 , @mehulmpt , i would like to work on this...
would you assign me the issue so that i can start wording on this

**Comment by Pranavtechie** [comment]
@amitanshusahu , you can work on this project
