### ISSUE TITLE
A TODO list website using HTMl, CSS, JS

### ISSUE THREAD

**Issue by iamrahul8** [codedamn/projects#158]
I want to work on this project
>It generally used to maintain our day-to-day tasks or list everything that we have to do, with the most important tasks at the top of the list, and the least important tasks at the bottom.

Please assign it to me under `hacktoberfest`

**Comment by Divjyo15** [comment]
hey can you assign me

**Comment by Pranavtechie** [comment]
https://codedamn.com/project/todo-app

https://codedamn.com/project/fullstack-todo-app

Hey @iamrahul8 , we already have two projects for different versions of todo-apps, you can work on a different project.
