### ISSUE TITLE
I want to add Online Calculator Clone

### ISSUE THREAD

**Issue by minhaj-313** [codedamn/projects#167]
I want to Contribute under Hacktoberfest Please assign me.
I want to Create a Calculator using HTML, CSS, and Javascript.
I saw YouTube Video on Codedamn Channel and then come to this Website then I did come here.
https://codedamn.com/hacktoberfest .
I want to contribute. Thank You.

**Comment by Pranavtechie** [comment]
@minhaj-313 , @Sonali3110 We already have a calculator clone on our projects page. https://codedamn.com/project/calculator-clone

**Comment by Pranavtechie** [comment]
You can work on a different project.
