### ISSUE TITLE
Genetic algorithm Simulation

### ISSUE THREAD

**Issue by Jam-Burger** [codedamn/projects#174]
The project will demonstrate how to use a genetic algorithm to simulate 'Evolution' in code.

I would like to work on this.

**Comment by Pranavtechie** [comment]
Hey @Jam-Burger , can you elaborate on the tech stack that will be used for this

**Comment by Jam-Burger** [comment]
The project is a visualization of the genetic algorithm. I can make the app using python graphic libraries or using normal HTML, CSS, and js.

**Comment by Pranavtechie** [comment]
Hey @Jam-Burger , it would be better if you can make it using HTML, CSS and JS. I hope you understand that you have to break down the project into individual steps and write instructions and challenges. I hope you have gone through the `Readme.md` file which mentions all the pointers.
