### ISSUE TITLE
I want to add Tic Tac Toe Game Using HTML, CSS, Javascript.

### ISSUE THREAD

**Issue by minhaj-313** [codedamn/projects#178]
I want to contribute Under Hacktoberfest.
Please Assign it to me.
Thank You.

**Comment by Soumya169** [comment]
i want to contribute for this please assign me

**Comment by Kaushalrr006** [comment]
assign me this task i am intrested
[GAME.zip](https://github.com/codedamn/projects/files/9857235/GAME.zip)
Please check it
