### ISSUE TITLE
portfolio website template

### ISSUE THREAD

**Issue by nikita812** [codedamn/projects#183]
hello,
i want to contribute an template for a good responsive portfolio website. please assign me this. 

**hacktoberfest22**

**Comment by Soumya169** [comment]
i want to contribute for portfolio web please assign me

**Comment by anshulsoni2010** [comment]
please assign me, I create an Amazing portfolio website template You can see my work. A portfolio website that I have to created https://anshulsoni.netlify.app , https://vijaykumarsoni.netlify.app
