### ISSUE TITLE
Instagram-reels-(REACT.JS and FIREBASE) 

### ISSUE THREAD

**Issue by Shubham1193** [codedamn/projects#188]
Hi! I would like to add a Instagram reels Clone here if you would allow. The clone can be made using React.js and Firebase as a backend  .The clone will have features like user login , signup , like comment on any reel and upload our own reel.
May I go ahead with this?
If yes, please assign this to me with hacktoberfest label.

**Comment by Pranavtechie** [comment]
Hey @Shubham1193, you can work on this
