### ISSUE TITLE
YouTube Playlist Length Calculator

### ISSUE THREAD

**Issue by ssahibsingh** [codedamn/projects#191]
YouTube Playlist Length Calculator calculates length of any youtube playlist over any custom range. Tech Stack used is Node.js, Express.js and YouTube Data API. Would like to make a guided project on this. Please assign this to me.

**Comment by Pranavtechie** [comment]
Hey @ssahibsingh, You can work on the guided project version of this

**Comment by ssahibsingh** [comment]
@Pranavtechie Thanks for assigning.

**Comment by ssahibsingh** [comment]
Hey @Pranavtechie , I have added a pull request for this issue. Please Review it. Issue #206
