### ISSUE TITLE
XharkTank : A MERN stack web-app.

### ISSUE THREAD

**Issue by sajdakabir** [codedamn/projects#242]
Hey i want to add a full stack XharkTank project.

What is XharkTank?
XharkTank is a platform where we connect new enthusiastic entrepreneurs to investors. Here, entrepreneurs can post their idea/pitches with their asked amount and exchangeable equity and investors can make a counteroffer.

**Comment by Pranavtechie** [comment]
Hey @sajdakabir , you can contribute your Project, make sure to go through our documentation on `Readme.md`. Feel free to ping me here if you have any doubts about setting up the guided project.
