### ISSUE TITLE
For Avoiding Similar projects Building.

### ISSUE THREAD

**Issue by VedantAndhale** [codedamn/projects#27]
Hi mehul sir and team codedamn,
As codedamn have a long list of projects can you please create a issue and then assign it to the folks who are working on the projects.
Because if their are 4 dev working on same project , then we would have same project with  different coding style. So if issue assign is done folks would know which is taken.
Then after the projects are on github we can work on together to improve coding style.
This will help everyone 
1. The dev who submitted it project would get a code review and know his mistake.
2. Newbie Would get more guided project.
@mehulmpt 
@Pranavtechie

**Comment by Pranavtechie** [comment]
Hey @VedantAndhale, this would be a good way to avoid working on the same project. Will update the guidelines
