### ISSUE TITLE
Working on Astral Portfolio Project

### ISSUE THREAD

**Issue by tamannasgh** [codedamn/projects#33]
may i work on this project?
https://codedamn.com/project/portfolio-project-html5

**Comment by Pranavtechie** [comment]
Hey @Tamanna-S , you can take this project and convert it into guided project

**Comment by RidhamRj** [comment]
@Pranavtechie hey i had a query regarding codedamn hacktoberfest
i would like to contribute the project
and just wanted to know what the project must include like is it neccesarily to be complete before conributing
or can i earn swag by just adding 1 of my project

**Comment by RidhamRj** [comment]
alright

**Comment by Tamanna-S** [comment]
thanks @Pranavtechie

**Comment by Tamanna-S** [comment]
hey! @Pranavtechie done check this out!
added astral-portfolio-page! #66

**Comment by Tamanna-S** [comment]
hey @Pranavtechie may you have a look now.
made astral-portfolio-page a guided project #72
