### ISSUE TITLE
Can i create meme generator  and contribute

### ISSUE THREAD

**Issue by Sambhav250703** [codedamn/projects#40]
I want to create meme generator and contribute in this project for hacktoberfest 2022 can I contribute ?

**Comment by Pranavtechie** [comment]
yes, you can work on the meme generator project.

**Comment by Sambhav250703** [comment]
Ok I will make a Project and make a pull request for it for merging thanks for replying

**Comment by Sambhav250703** [comment]
[Meme Generator](https://github.com/codedamn/projects/pull/56)
Pls check to he pr raise for it

**Comment by Sambhav250703** [comment]
Hi @Pranavtechie  I have made the required changes in the pr pls verify it again

**Comment by Pranavtechie** [comment]
Hey @Sambhav250703 , will do and share the comments in the PR itself

**Comment by Sambhav250703** [comment]
Okk 👍👍

**Comment by Sambhav250703** [comment]
Hey @Pranavtechie 
Sorry to disturb you but can u pls check my pr and tell me is their error any in the pull request or else can you merge so it will help me to count in the hacktoberfest 2022 contribution 
Thanks and again sorry for disturbing you
