### ISSUE TITLE
Added Netflix Clone

### ISSUE THREAD

**Issue by manmohan4142** [codedamn/projects#67]
Can I contribute to this project of netflix clone?? please tell me @Pranavtechie

**Comment by Pranavtechie** [comment]
Hey @manmohan4142 , you can contribute this project

**Comment by Kpallavi5** [comment]
Hyy @Pranavtechie I'm interested to work on this project can you please assign me so that I can start working on this project....?

**Comment by Kpallavi5** [comment]
@Pranavtechie ?
