### ISSUE TITLE
Basic Clock web app using Js for beginners 

### ISSUE THREAD

**Issue by Shreyas-SAS** [codedamn/projects#69]
Hey!
I would like to add a simple project of building a clock application with different changeable themes here if you would allow. 
It will be based on only HTML, CSS and Javascript so that early starters can also attempt building it. 
Can I go ahead with it?
If yes, please assign it to me with hactoberfest label.

**Comment by Pranavtechie** [comment]
Yes @Shreyas-SAS, you can proceed with making the guided-project

**Comment by bhaskar08** [comment]
Hey @Shreyas-SAS, you are already doing one issue right, so can I please take up this issue, I have a limited knowledge about web dev and given that I have already made a similar project, I would love to do this specific issue. Is it ok If I do this one and you do the other one?

**Comment by Shreyas-SAS** [comment]
@bhaskar08 oh ok. I have not started with this project yet and given that this is your first issue I can lend you this one, I am left with just 1 issue for my 4 PR goal and that would complete with the other project so its ok if you do that. @Pranavtechie can you please assign @bhaskar08 with this issue. I will help him if he gets stuck anywhere so it won't be a problem. Happy coding.

**Comment by bhaskar08** [comment]
Oh Thanks @Shreyas-SAS . I will consult you if I get stuck anywhere. @Pranavtechie please assign this issue to me. I will do it perfectly with support from @Shreyas-SAS.

**Comment by mehulmpt** [comment]
You can work on it. Please send a PR when you're ready. Read the guidelines here: https://github.com/codedamn/projects#readme
