### ISSUE TITLE
Basic Drawing application using Js

### ISSUE THREAD

**Issue by Shreyas-SAS** [codedamn/projects#70]
Hey! 
I would like to create another mini project of a drawing app for complete beginners who only know HTML, CSS and Javascript to give theme a base development experience in an early stage of development career. 
Can I go ahead with it? If yes, please add hacktoberfest label and assign it to me. 
Thanks.

**Comment by Pranavtechie** [comment]
Hey @Shreyas-SAS, you can pick this project up as well

**Comment by Abhir1902** [comment]
I have created a smart board application which will be useful for the same. Please check https://github.com/Abhir1902/Pencil-box. 
Also have a look at the website link attached in the description.

**Comment by Pranavtechie** [comment]
Hey @Abhir1902 , we currently do not functionality to run flutter apps on Codedamn Playgrounds, so it is not very suitable to share a guided version of your flutter project here. If you have any web based or web3/blockchain based applications you can contribute them here.

**Comment by Abhir1902** [comment]
@Pranavtechie actually I have made the project using HTML, CSS , JavaScript and Firebase.

**Comment by mehulmpt** [comment]
You can work on it. Please send a PR when you're ready. Read the guidelines here: https://github.com/codedamn/projects#readme
