### ISSUE TITLE
Interactive banner page having better UI/UX

### ISSUE THREAD

**Issue by HeisRoy33** [codedamn/projects#71]
Hey!
I would like to add a simple project of building a banner page with different changeable themes, dark mode and light mode here if you would allow.
It will be based on only HTML, CSS, SCSS and Javascript so that early starters can also attempt building it.
Can I go ahead with it?
If yes, please assign it to me with hacktoberfest label.

**Comment by Pranavtechie** [comment]
Hey @HeisRoy33, yes you can go ahead with the project. Make sure to convert this project into a guided-project. Make sure that you understand the instructions given in the README.md file. Feel free to ask any doubts here.
