### ISSUE TITLE
A wordle-like game using vanilla javascript

### ISSUE THREAD

**Issue by Suman373** [codedamn/projects#75]

**Comment by Suman373** [comment]
Can I work on this issue admin/moderator?

**Comment by Pranavtechie** [comment]
Hey @Suman373 , @somyasubham9 . We are already a hard level project for wordle-clone https://codedamn.com/project/custom-wordle-clone

Any one of you can choose to update the current project or create a new project of your choice

**Comment by Suman373** [comment]
> Hey @Suman373 , @somyasubham9 . We are already a hard level project for wordle-clone https://codedamn.com/project/custom-wordle-clone
> 
> Any one of you can choose to update the current project or create a new project of your choice

I will try to upload any other project. Thanks

**Comment by Suman373** [comment]
Since there is already a project on wordle. I am closing this issue
