### ISSUE TITLE
beginner: A Basic Movie Details Showing Website using HTML + CSS + JS + API for beginners

### ISSUE THREAD

**Issue by Zaheer-zk** [codedamn/projects#84]
#81 Hi, I have added a project which is basically a website which show the latest movie. In this project get to know how to use api, how to manipulate data in API and how to use that data which can help in many scenarios. learning for some Beginner++ Level student.

**Comment by Pranavtechie** [comment]
Hey @Zaheer-zk, thanks for contributing this project, make sure to mention this issue in your PR
