### ISSUE TITLE
Real-estate-website

### ISSUE THREAD

**Issue by shubhra-g** [codedamn/projects#86]
Hey!
I would like to add a simple project of building a real estate website .
If yes, please assign it to me with hactoberfest label.

**Comment by shubhra-g** [comment]
can you please assign me to this issue ? @Pranavtechie

**Comment by Pranavtechie** [comment]
Hey @shubhra-g , I've assigned. You can start working on the guided-project

**Comment by shubhra-g** [comment]
PR #185

**Comment by shubhra-g** [comment]
PR #185

**Comment by shubhra-g** [comment]
Hey can you check the Pull Request #238
