### ISSUE TITLE
Add : Tours details app in react

### ISSUE THREAD

**Issue by Suman373** [codedamn/projects#87]

**Comment by Suman373** [comment]
I want to work on this project from scratch. Pls assign me

**Comment by Pranavtechie** [comment]
Hey @Suman373, It's ideal to create a guided-project once you have completed the your project first.

**Comment by Pranavtechie** [comment]
I'm assigning this to you for now, but make sure that you go through all the instructions mentioned in the in `README.md`

**Comment by Suman373** [comment]
> Hey @Suman373, It's ideal to create a guided-project once you have completed the your project first.

I know, I will write the instructions. Is there any time limit for pulling request?
