### ISSUE TITLE
A basic site showing codeforces details

### ISSUE THREAD

**Issue by Perseus-Jackson477** [codedamn/projects#88]
I wish to create a basic website showing details of any person's codeforces profile. This will help in learning HTML, CSS, JS and APIs as well. May I work on this project?

**Comment by Pranavtechie** [comment]
Hey @Perseus-Jackson477 , you can work on the guided project for this, but make sure that you completed the actual project before converting it to a guided project as it will be an easy process and removes all the ambiguity
