### ISSUE TITLE
bmi-calculator

### ISSUE THREAD

**Issue by Hariprasad19036** [codedamn/projects#96]
I would like to contribute a BMI Calculator app created using React under the hacktoberfest label. Kindly assign this issue to me.

**Comment by Pranavtechie** [comment]
Hey @Hariprasad19036 , there is already a small BMI Calculator that is already being reviewed. 
https://github.com/codedamn/projects/pull/39

Even though the tech stack for the project seems to be different, I think it is best for you to work on a different project altogether

**Comment by Hariprasad19036** [comment]
Sure, thanks!
