### ISSUE TITLE
PDF merger website

### ISSUE THREAD

**Issue by Hariprasad19036** [codedamn/projects#98]
I would like to create a website that can merge multiple pdfs using Flask and PyPDF2. Kindly assign this issue to me with the hacktoberfest label.

**Comment by Pranavtechie** [comment]
Hey @Hariprasad19036 , you would have to create a guided-project for this once you are done with the project. I hope you understand the Instructions given

**Comment by Hariprasad19036** [comment]
Thanks @Pranavtechie! I've created a guided project and raised a PR for review.
